# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.isSorted <- function(dataFrame, indexes, ascending) {
    .Call(`_Andromeda_isSorted`, dataFrame, indexes, ascending)
}

.isSortedVectorList <- function(vectorList, ascending) {
    .Call(`_Andromeda_isSortedVectorList`, vectorList, ascending)
}

